name: soundmates
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.21.2
  beamer: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  custom_lint:
  riverpod_lint: ^2.6.5

flutter:
  uses-material-design: true
