name: soundmates
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  beamer: ^1.7.0
  equatable: ^2.0.7
  firebase_analytics: ^11.4.4
  firebase_core: ^3.12.1
  firebase_crashlytics: ^4.3.4
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_dotenv: ^5.2.1
  flutter_hooks: ^0.21.2
  fpdart: ^1.1.1
  get_it: ^8.0.3
  hooks_riverpod: ^2.6.1
  hydrated_bloc: ^10.0.0
  logging: ^1.3.0
  shared_preferences: ^2.5.2
  vector_graphics: ^1.1.18

dev_dependencies:
  custom_lint: null
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  riverpod_lint: ^2.6.5
  vector_graphics_compiler: ^1.1.16

flutter:
  uses-material-design: true
  assets:
    - .env
    - path: assets/images/
      transformers:
        - package: vector_graphics_compiler
    - path: assets/icons/
      transformers:
        - package: vector_graphics_compiler
