name: soundmates
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.21.2
  beamer: ^1.7.0
  equatable: ^2.0.7
  fpdart: ^1.1.1
  firebase_core: ^3.12.1
  firebase_crashlytics: ^4.3.4
  firebase_analytics: ^11.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  custom_lint:
  riverpod_lint: ^2.6.5

flutter:
  uses-material-design: true
